### ISSUE TITLE
Can't resolve './tailwind.css'

### ISSUE THREAD

**Issue by GithubJaimeLee** [saifulshihab/facebook-clone#1]
./src/App.jsx
Module not found: Can't resolve './tailwind.css' in '/facebook-clone/src'

**Comment by saifulshihab** [comment]
@nyjackielee did you build the CSS first?

**Comment by GithubJaimeLee** [comment]
> @nyjackielee did you build the CSS first?

Should I use yarn build css first? I usually use npm. When 'npm start' It reported that can not find main.css, without main.css… the webside looks … not good looking. But I have checked your github homepage. Wonderful.

**Comment by saifulshihab** [comment]
@nyjackielee run this command `yarn build:tailwindcss` or `npm run build:tailwindcss` first. This will generate that `tailwind.css` file. Then restart the app.
